# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=250)),
                ('serial', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='invent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Inventory'),
        ),
    ]
