# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru_inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='Serial',
            field=models.CharField(max_length=50),
        ),
    ]
