# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru_inv', '0002_auto_20161017_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='Serial',
            new_name='serial',
        ),
    ]
